"""Refazendo Tabela Carros

Revision ID: 29b27b5ab2e5
Revises: 790ae120d392
Create Date: 2024-05-08 21:36:20.647775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b27b5ab2e5'
down_revision: Union[str, None] = '790ae120d392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('placa', sa.String(length=7), nullable=True),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.Column('proprietario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proprietario_id'], ['proprietarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carros_modelo'), 'carros', ['modelo'], unique=False)
    op.create_index(op.f('ix_carros_placa'), 'carros', ['placa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carros_placa'), table_name='carros')
    op.drop_index(op.f('ix_carros_modelo'), table_name='carros')
    op.drop_table('carros')
    # ### end Alembic commands ###
