"""Alterando a tabela proprietarios

Revision ID: 32fe2e1f5bce
Revises: f8b3c9798fb2
Create Date: 2024-05-08 21:08:28.179412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32fe2e1f5bce'
down_revision: Union[str, None] = 'f8b3c9798fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proprietarios', sa.Column('cpf', sa.String(length=11), nullable=True))
    op.add_column('proprietarios', sa.Column('endereco', sa.String(length=100), nullable=True))
    op.add_column('proprietarios', sa.Column('numero_telefone', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_proprietarios_cpf'), 'proprietarios', ['cpf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proprietarios_cpf'), table_name='proprietarios')
    op.drop_column('proprietarios', 'numero_telefone')
    op.drop_column('proprietarios', 'endereco')
    op.drop_column('proprietarios', 'cpf')
    # ### end Alembic commands ###
