"""Add tabela carros

Revision ID: e267d4313ee8
Revises: 32fe2e1f5bce
Create Date: 2024-05-08 21:29:50.040191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e267d4313ee8'
down_revision: Union[str, None] = '32fe2e1f5bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
