"""Alterando name para nome

Revision ID: f8b3c9798fb2
Revises: 1c780ee64350
Create Date: 2024-05-08 20:36:16.873832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b3c9798fb2'
down_revision: Union[str, None] = '1c780ee64350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proprietarios', sa.Column('nome', sa.String(length=50), nullable=True))
    op.drop_index('ix_proprietarios_name', table_name='proprietarios')
    op.create_index(op.f('ix_proprietarios_nome'), 'proprietarios', ['nome'], unique=False)
    op.drop_column('proprietarios', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proprietarios', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_proprietarios_nome'), table_name='proprietarios')
    op.create_index('ix_proprietarios_name', 'proprietarios', ['name'], unique=False)
    op.drop_column('proprietarios', 'nome')
    # ### end Alembic commands ###
